---
version: 1
formatters:
  main:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%d-%m-%y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: main
    stream: ext://sys.stdout
loggers:
  mainLogger:
    level: INFO
    handlers: [ console ]
    propagate: no
root:
  level: INFO
  handlers: [ console ]
...